name: .NET master

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Pack
      run: dotnet pack --no-restore --no-build --configuration Release --output nupkgs
    - name: Push
      env:
         NUGET_KEY: ${{ secrets.NUGET_KEY }}
      run: dotnet nuget push .\nupkgs\** --api-key "$NUGET_KEY" --source https://api.nuget.org/v3/index.json
